# PATH VARIABLES _________________________________________________________________________________________
BASE_IMG_PATH = 'Data\\Images\\'
MAP_PATHS = "Data\\Maps\\"

# TILE MAP SPECIFIC TO BE ADDED TO WHEN ADDING TILE SETS TO THE TILES DIRECTORY __________________________
# Player collide-able tiles
# ** Add to this for the editor to load them **
PHYSICS_TILES = {'grass_1'}
# Tiles that can be auto tiled and txt file that came from tile-setter
# ** Add to this for the editor to load them **
AUTOTILE_TYPES = {'grass_1'}
# Objects types that the player can interact with **Must match the Tile_Set_Paths keys**
OBJECT_TYPES = ['objects']
# Text file generated by tile-setter with the calculations for tile placement (Auto tiling)
# ** Add to this for the editor to load them **
RULE_PATHS = [
              ('grass_1', "Tiles/grass_1/grass_1.txt"),
              ]
# All the assets for the editor to use
# ** Add to this for the editor to load them **
TILE_SETS_PATHS = {
                   'grass_1': 'Tiles/grass_1/grass_1.png',
                   }
# TILE MAP SPECIFIC DO NOT CHANGE ________________________________________________________________________
NORTHWEST = 1
NORTH = 2
NORTHEAST = 4
EAST = 8
SOUTHEAST = 16
SOUTH = 32
SOUTHWEST = 64
WEST = 128

N = (0, -1)
S = (0, 1)
E = (1, 0)
W = (-1, 0)
NW = (-1, -1)
NE = (1, -1)
SE = (1, 1)
SW = (-1, 1)

BITMASK_LOOKUP = {
    N: NORTH,
    E: EAST,
    S: SOUTH,
    W: WEST,
    NW: NORTHWEST,
    NE: NORTHEAST,
    SE: SOUTHEAST,
    SW: SOUTHWEST
}

DIRECTION_LOOKUP = {
    NW: [E, S],
    NE: [W, S],
    SE: [N, W],
    SW: [N, E]
}
